; Super Memory Knowledge Base
; Saved: 2026-09-29T09:32:40.958338+00:00
; Session: d012741076f2

(Department AerospaceEngineering)
(Department AppliedMechanicsAndBiomedicalEngineering)
(Department Biotechnology)
(Department ChemicalEngineering)
(Department Chemistry)
(Department CivilEngineering)
(Department ComputerScienceAndEngineering)
(Department DataScienceAndArtificialIntelligence)
(Department ElectricalEngineering)
(Department EngineeringDesign)
(Department HumanitiesAndSocialSciences)
(Department ManagementStudies)
(Department Mathematics)
(Department MechanicalEngineering)
(HasClearance Anush Level3)
(RequiresClearance LabAlpha Level3)
